name: CI

on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      # Setting environment variables for NextAuth
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'test-ci-secret-for-demo-purposes-only' }}
      NEXTAUTH_URL: http://localhost:3000

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint:fix

      - name: Type check
        run: npm run type-check

      - name: Run unit tests
        run: npm test

      - name: Install Playwright Browsers
        run: npm run setup:e2e

      - name: Build application for E2E testing
        run: npm run build

      - name: Run E2E tests
        run: npm run e2e

  # Commented out Vercel deployment jobs because they require secrets not set in GitHub
  # To enable deployment, add VERCEL_TOKEN, VERCEL_ORG_ID, and VERCEL_PROJECT_ID
  # secrets to your GitHub repository

  # deploy-preview:
  #   needs: build-and-test
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #
  #     - name: Deploy to Vercel (Preview)
  #       uses: amondnet/vercel-action@v25
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         working-directory: ./
  #
  # deploy-production:
  #   needs: build-and-test
  #   if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #
  #     - name: Deploy to Vercel (Production)
  #       uses: amondnet/vercel-action@v25
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         vercel-args: '--prod'
  #         working-directory: ./
